let img = document.getElementById("Filme");
let IMDB = document.getElementById("imdb");
let nomeFilme = document.getElementById("Nome");
let descricao = document.getElementById("Sinopse");
let avaliacao = document.getElementById("Nota");

function imagem(){
    descricao.style.border = '2px solid #ccc';
    const filmes = [
        { nome: "Vingadores: Ultimato", imagem: "Assets/Imagens/VingadoresUltimato.jpg", nota: "8,4/10", sinopse: "Após Thanos eliminar metade das criaturas vivas, os Vingadores têm de lidar com a perda de amigos e entes queridos. Com Tony Stark vagando perdido no espaço sem água e comida, Steve Rogers e Natasha Romanov lideram a resistência contra o titã louco."},
        { nome: "Cruella", imagem: "Assets/Imagens/Cruella.png", nota: "7,3/10", sinopse: "Inteligente, criativa e determinada, Estella quer fazer um nome para si através de seus designs e acaba chamando a atenção da Baronesa Von Hellman. Entretanto, o relacionamento delas desencadeia um curso de eventos e revelações que fazem com que Estella abrace seu lado rebelde e se torne a Cruella, uma pessoa má, elegante e voltada para a vingança." },
        { nome: "Mundo em Caos", imagem: "Assets/Imagens/Mundo em Caos.png", nota: "5,7/10", sinopse: "Todd cresceu com a crença de que as mulheres desapareceram do mundo e os homens foram afetados por um ruído capaz de deixar seus pensamentos audíveis. Ele então descobre um pedaço de silêncio no pântano, onde encontra uma garota chamada Viola. Todd jura protegê-la, mas para isso deve descobrir sua força e desvendar todos os segredos sombrios que seu planeta e sua comunidade guardam." },
        { nome: "O jogo da imitação", imagem: "Assets/Imagens/O jogo da imitação.png", nota: "8,0/10", sinopse: "Em 1939, a recém-criada agência de inteligência britânica MI6 recruta Alan Turing, um aluno da Universidade de Cambridge, para entender códigos nazistas, incluindo o Enigma, que criptógrafos acreditavam ser inquebrável. A equipe de Turing, incluindo Joan Clarke, analisa as mensagens de Enigma, enquanto ele constrói uma máquina para decifrá-las. Após desvendar as codificações, Turing se torna herói. Porém, em 1952, autoridades revelam sua homossexualidade, e a vida dele vira um pesadelo." },
        { nome: "Rampage", imagem: "Assets/Imagens/Rampage.png", nota: "6,1/10", sinopse: "Davis Okoye é um primatologista, um homem recluso que compartilha um vínculo inabalável com George, um gorila muito inteligente que está sob seus cuidados desde o nascimento. Quando um experimento genético desonesto é feito em um grupo de predadores que inclui o primata, os animais se transformam em monstros que destroem tudo em seu caminho. Agora, Okoye precisa conseguir um antídoto e impedir que seu amigo provoque uma catástrofe global." },
        { nome: "Tomb Raider", imagem: "Assets/Imagens/Tomb Raider.png", nota: "6,3/10", sinopse: "Lara Croft é a independente filha de um aventureiro excêntrico que desapareceu há anos. Com a esperança de resolver o mistério do sumiço de seu pai, Lara embarca em uma perigosa jornada para seu último destino conhecido - um túmulo lendário em uma ilha mítica que pode estar em algum lugar ao largo da costa do Japão. As apostas não podiam ser maiores, pois Lara precisa confiar em sua mente aguda, fé cega e espírito obstinado para se aventurar no desconhecido." },
        { nome: "Um lugar silencioso 2", imagem: "Assets/Imagens/Um Lugar Silencioso 2.png", nota: "7,2/10", sinopse: "A família Abbott precisa enfrentar os terrores do mundo exterior enquanto luta pela sobrevivência em silêncio. Forçados a se aventurar no desconhecido, eles percebem que as criaturas que caçam pelo som não são as únicas ameaças no caminho da areia." },
        { nome: "Um lugar silencioso", imagem: "Assets/Imagens/Um lugar silencioso.png", nota: "7,5/10", sinopse: "Em uma fazenda nos Estados Unidos, uma família do Meio-Oeste é perseguida por uma entidade fantasmagórica assustadora. Para se protegerem, eles devem permanecer em silêncio absoluto, a qualquer custo, pois o perigo é ativado pela percepção do som." },
        { nome: "Uncharted", imagem: "Assets/Imagens/Uncharted.png", nota: "6,3/10", sinopse: "Nathan Drake e seu parceiro canastrão Victor Sully Sullivan embarcam em uma perigosa busca para encontrar o maior tesouro jamais encontrado. Enquanto isso, eles também rastreiam pistas que podem levar ao irmão perdido de Nathan." },
        { nome: "Velozes e Furiosos 5", imagem: "Assets/Imagens/Velozes e Furiosos 5.png", nota: "7,3/10", sinopse: "Desde que o ex-policial Brian O'Conner e Mia Toretto libertaram Dom da prisão, eles viajam pelo mundo para fugir das autoridades. No Rio de Janeiro, eles são obrigados a fazer um último trabalho antes de ganhar sua liberdade definitiva. Brian e Dom montam uma equipe de elite de pilotos de carro para executar a tarefa, mas precisam enfrentar um empresário corrupto e também um obstinado agente federal norte-americano." },
        { nome: "A Freira", imagem: "Assets/Imagens/A freira.png", nota: "5,3/10", sinopse: "Presa em um convento na Romênia, uma freira comete suicídio. Para investigar o caso, o Vaticano envia um padre assombrado e uma noviça prestes a se tornar freira. Arriscando suas vidas, a fé e até suas almas, os dois descobrem um segredo profano e se confrontam com uma força do mal que toma a forma de uma freira demoníaca e transforma o convento em um campo de batalha." },
        { nome: "Adão Negro", imagem: "Assets/Imagens/Adao_Negro.png", nota: "6,2/10", sinopse: "O poderoso Adão Negro é libertado de sua tumba para lançar sua justiça cruel sobre a Terra." },
        { nome: "Alerta Vermelho", imagem: "Assets/Imagens/Alerta_Vermelho.png", nota: "6,3/10", sinopse: "Um alerta vermelho da Interpol é emitido e o agente do FBI John Hartley assume o caso. Durante sua busca, ele se vê diante de um assalto ousado e é forçado a se aliar ao maior ladrão de arte da história, Nolan Booth, para capturar a ladra de arte mais procurada do mundo atualmente, Sarah Black." },
        { nome: "Avatar: O Caminho da Água", imagem: "Assets/Imagens/Avatar.png", nota: "7,6/10", sinopse: "Após formar uma família, Jake Sully e Ney'tiri fazem de tudo para ficarem juntos. No entanto, eles devem sair de casa e explorar as regiões de Pandora quando uma antiga ameaça ressurge, e Jake deve travar uma guerra difícil contra os humanos." },
        { nome: "The Batman", imagem: "Assets/Imagens/Batman.png", nota: "7,3/10", sinopse: "Após dois anos espreitando as ruas como Batman, Bruce Wayne se encontra nas profundezas mais sombrias de Gotham City. Com poucos aliados confiáveis, o vigilante solitário se estabelece como a personificação da vingança para a população." },
        { nome: "Besouro Azul", imagem: "Assets/Imagens/Besouro_Azul.png", nota: "7,8/10", sinopse: "O adolescente Jaime Reyes ganha superpoderes quando um misterioso escaravelho se prende à sua coluna e lhe fornece uma poderosa armadura alienígena azul." },
        { nome: "Bird Box", imagem: "Assets/Imagens/Bird_Box.png", nota: "6,6/10", sinopse: "Entidades misteriosas invadem a Terra com sua terrível presença. Aqueles que as veem, se matam instantaneamente. O mundo entra em colapso, mas uma mãe luta para encontrar um lugar seguro para viver com seus filhos." },
        { nome: "Cabras da Peste", imagem: "Assets/Imagens/Cabras_Da_Pestepng.png", nota: "6,0/10", sinopse: "Bruceuilis, um policial do interior do Ceará, viaja até São Paulo para resgatar Celestina, uma cabra considerada patrimônio de sua cidade. Na capital paulista, ele encontra Trindade, um escrivão da polícia que decide sair do marasmo de seu trabalho e ajudá-lo na aventura, mesmo não sendo sua especialidade." },
        { nome: "Free Guy", imagem: "Assets/Imagens/Free_Guy.png", nota: "7,1/10", sinopse: "Um caixa de banco preso a uma entediante rotina tem sua vida virada de cabeça para baixo quando descobre que é um personagem em um jogo interativo. Agora ele precisa aceitar sua realidade e lidar com o fato de que é o único que pode salvar o mundo." },
        { nome: "Gran Turismo", imagem: "Assets/Imagens/Gran_Turismo.png", nota: "7,2/10", sinopse: "O jovem Jann Mardenborough vence uma série de competições do vídeo-game Gran Turismo, promovidas por uma grande empresa automobilística, e ganha a oportunidade de se tornar um piloto profissional." },
        { nome: "It - A Coisa", imagem: "Assets/Imagens/It.png", nota: "7,3/10", sinopse: "Um grupo de crianças se une para investigar o misterioso desaparecimento de vários jovens em sua cidade. Eles descobrem que o culpado é Pennywise, um palhaço cruel que se alimenta de seus medos e cuja violência teve origem há vários séculos." },
        { nome: "John Wick", imagem: "Assets/Imagens/John_Wick.png", nota: "7,4/10", sinopse: "John Wick é um lendário assassino de aluguel aposentado, lidando com o luto após perder o grande amor de sua vida. Quando um gângster invade sua casa, mata seu cachorro e rouba seu carro, ele é forçado a voltar à ativa e inicia sua vingança." },
        { nome: "Mistério no Mediterrâneo", imagem: "Assets/Imagens/Misterio_No_Mediterraneo.png", nota: "6,0/10", sinopse: "Em uma incrível viagem à Europa, um policial de Nova York e sua esposa cabeleireira tentam solucionar um caso de assassinato a bordo do iate de um bilionário." }
    ];

    IMDB.src = "Assets/Imagens/imdb.png";
    const filmeAleatorio = filmes[Math.floor(Math.random() * filmes.length)];
    img.src = filmeAleatorio.imagem;
    nomeFilme.innerHTML = filmeAleatorio.nome;
    descricao.innerHTML = filmeAleatorio.sinopse;
    avaliacao.innerHTML = filmeAleatorio.nota;

    return false;
}